name: "CD"

on:
  workflow_dispatch:

permissions:
  contents: "read"

jobs:
  nix:
    runs-on: "ubuntu-latest"
    container:
      image: "docker.io/nixos/nix@sha256:b9c9611c8530fa8049a1215b20638536e1e71dcaf85212e47845112caf3adeea"
      env:
        NIX_CONFIG: "experimental-features = nix-command flakes"
    steps:
      - name: "GitHub: Checkout Repository"
        uses: "actions/checkout@v6"
      - name: "Task: CD"
        shell: >
          nix develop
          --ignore-env
          --keep-env-var HOME
          --keep-env-var NIX_CONFIG
          .#cdEnvironment
          -c bash -eo pipefail {0}
        run: "task run:workflow WORKFLOW_NAME='cd'"
