name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: "read"

env:
  DOCKER_HOST: "tcp://docker:2375"
  TESTCONTAINERS_RYUK_DISABLED: "true"

jobs:
  nix:
    runs-on: "ubuntu-latest"

    container:
      image: "docker.io/nixos/nix@sha256:b9c9611c8530fa8049a1215b20638536e1e71dcaf85212e47845112caf3adeea" # v2.34.0
      env:
        NIX_CONFIG: "experimental-features = nix-command flakes"

    services:
      docker:
        image: "docker:28.4-dind"
        env:
          DOCKER_TLS_CERTDIR: ""
        options: >-
          --privileged

    steps:
      - name: "GitHub: Checkout Repository"
        run: |
          git init --quiet --initial-branch "main"
          git config --global --add safe.directory "*"
          git remote add origin "${{ github.server_url }}/${{ github.repository }}"
          git config --local http.${{ github.server_url }}/.extraheader "Authorization: basic $(echo -n "x-access-token:${{ github.token }}" | base64 --wrap=0)"
          git fetch --quiet --no-tags --depth=1 origin "${{ github.ref }}"
          git checkout --quiet "${{ github.sha }}"
      - name: "Task: CI"
        shell: >
          nix develop
          --ignore-env
          --keep-env-var CI
          --keep-env-var HOME
          --keep-env-var NIX_CONFIG
          --keep-env-var DOCKER_HOST
          --keep-env-var TESTCONTAINERS_RYUK_DISABLED
          .#ciEnvironment
          -c bash -eo pipefail {0}
        run: "task run:workflow WORKFLOW_NAME='ci'"
